name: CICD workflow

# Update to the tag of hte code release you want to push
env:
  TAG_VERSION: 1.0.0

# on:
#   # Trigger the workflow on push events to the "test" branch
#   push:
#     branches:
#       - test

#   # Trigger the workflow on pull request events for the "test" branch
#   pull_request:
#     branches:
#       - test

on:
  # Allows the workflow to be manually triggered
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

  PyTest:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Pytest
        run: |
          echo Simulating that we are running PyTests
          echo I will add tests later
          

  Push_code_to_test_branch:
    needs: PyTest
    runs-on: ubuntu-latest
    steps:

      # Do I need to checkout the code here if I have a job like Build above?
      #- name: Checkout code
      #  uses: actions/checkout@v3

      - name: Push code
        run: |
          # git push origin dev:test --force
          echo This is the TAG_VERSION variable: $TAG_VERSION
