name: CICD workflow

env:
  PYTHON_VERSION: 3.9

on:
  pull_request:
    branches:
    # pull_request event to listen for changes on the test branch
      - test
  # Allows the workflow to be manually triggered
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      # Should be in all workflows, almost. It tells github actions to download the content of my repo to my Runner (a VM). 
      # All other operations may access that code now
        uses: actions/checkout@v3

  PyTest:
    needs: Build
    runs-on: ubuntu-latest
    steps: 
      # Test to remove this actions
      - uses: actions/checkout@v3  
      - name: Set up Python ${{ env.MY_VAR }} 
        uses: actions/setup-python@v4  
        with:  
          python-version: ${{ env.MY_VAR }}  
      - name: Install dependencies  
        run: |  
          python -m pip install --upgrade pip  
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi    
      - name: Test with pytest  
        run: |  
          coverage run -m pytest  -v -s  
      - name: Generate Coverage Report  
        run: |  
          coverage report -m


  
          
