name: CICD workflow

on:
  pull_request:
    branches:
    # pull_request event to listen for changes on the test branch
      - test
  # Allows the workflow to be manually triggered
  workflow_dispatch:

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
      # Should be in all workflows, almost. It tells github actions to download the content of my repo to my Runner (a VM). 
      # All other operations may access that code now
        uses: actions/checkout@v3

  PyTest:
    needs: Build
    runs-on: ubuntu-latest
    steps:
      - name: Run Pytest
        run: |
          echo Simulating that we are running PyTests
          echo I will add tests later
          
